Add "__repr__" and "print_grid" to itemized_resource to display item occupacy (#127)
* Add "__repr__" to itemized_resource, displaying a grid of occupied/free spots

Example output:

```
12x8 TipRack
    1  2  3  4  5  6  7  8  9  10 11 12
A:  -  -  -  -  -  -  -  -  -  -  -  -
B:  -  -  -  -  -  -  -  -  -  -  -  -
C:  -  -  -  -  -  -  -  -  -  -  -  -
D:  -  -  -  -  -  -  -  -  -  -  -  -
E:  -  -  -  -  -  -  -  -  -  -  -  -
F:  -  -  -  -  -  -  -  -  -  -  -  -
G:  -  -  -  -  -  -  -  -  -  -  -  -
H:  -  -  -  -  -  -  -  -  -  -  -  -
```

* Add LETTERS

* linter errors

* fix type checking

* fix type checking again

pylabrobot/resources/itemized_resource.py:390: error: Incompatible types in assignment (expression has type "str", variable has type "list[list[str]]")  [assignment]
pylabrobot/resources/itemized_resource.py:393: error: Unsupported operand types for + ("str" and "list[list[str]]")  [operator]

* replace __repr__ with print_grid

makes more sense, and is required because there is no way for itemizedresource way to know how to check for or represent the items from classes inheriting from it (see comments in code)

* add footer

* _occupied_func: replace Resource hint with T

"T is a placeholder for the resource that is "itemized" by ItemizedResource. It is TipSpot for TipRack, Well for Plate, and Tube (soon TubeSpot) for TubeRacks"

* Add _occupied_func method to TipRack

This overrides _occupied_func in ItemizedResource, making print_grid informative about tips in tipspots

* linter fixes

* fix typo